### PR TITLE
Complete the 3 R's

### PR DESCRIPTION
**Pull request by seanfreiburg**
Reduce was missing from the 3 R's we learned in school. Spec is here: https://www.epa.gov/recycle

### CODE REVIEW

**Comment by saket** [comment]
sorry, this is a really long PR. can you split this in multiple commits so that it's easier to review?

**Comment by seanfreiburg** [comment]
@saket I'll have to see, maybe I can buy Q3?

**Comment by saket** [comment]
sounds good, make sure you follow agile development

**Comment by mattprecious** [comment]
I fundamentally disagree with this change. In order to properly reduce, we need to impose a limit on the number of items added to the adapter. Please draft a 5 page design document and let's take this offline.

**Comment by AlecKazakova** [comment]
i was thinking of making this change myself, can you close yours please

**Comment by saket** [comment]
any updates on this?

**Comment by psuzn** [comment]
@seanfreiburg You might need to change things here because this breaks the `SOLID` principle into liquid and probably into gases.

**Comment by saket** [comment]
hey I'm still reviewing this PR

**Comment by seanfreiburg** [comment]
Closing as I've learned Reduce is much more powerful than Recycler or Reuse and should not be associated with them.

**Pull request closed without merging**
